### ISSUE TITLE
Feature request: ability to specify a year in which the week number is to be interpreted

### ISSUE THREAD

**Issue by guijemont** [mrobinson/phpreport-report#8]
I just wanted to generate a report for week 52 of 2014, and there doesn't seem to be a way to do it now that we're in 2015. Ideally, I'd like to be able to do something like:
```
  phpreport-report -l $LOGIN -u $USER -w 52 -y 2014
```

**Comment by guijemont** [comment]
Looking at the code, I see that I can do `-w 52/2014` though it's not documented.

**Comment by guijemont** [comment]
Proposed fix: #9

**Comment by mrobinson** [comment]
I think this is fixed by #9. Feel free to reopen if it's not.
